version: '3'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    depends_on:
      - db
      - migration
  migration:
    build:
      context: app
    command: python manage.py migrate --noinput
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
        POSTGRES_USER: apsiadmin
        POSTGRES_PASSWORD: password
        POSTGRES_DB: apsi
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  pgdata: