version: '3'

services:
  web:
    build:
      context: app
    ports:
      - '8000:8000'
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
        POSTGRES_USER: apsiadmin
        POSTGRES_PASSWORD: password
        POSTGRES_DB: apsi
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  pgdata: